services:
  vpn-app:
    build: .
    container_name: vpn-app
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: no
    volumes:
      - ./cfg:/cfg
    networks:
      - vpnnet
      - app-network
      - flareproxyserver_app-network

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    networks:
      - vpnnet
    volumes:
      - mongo-data:/data/db
    logging:
      driver: "none"

volumes:
  mongo-data:

networks:
  vpnnet:
    driver: bridge
  app-network:
    driver: bridge
  flareproxyserver_app-network:
    external: true
